
# Top-level Makefile for OpenLCB C/C++ implementations

all: 
	# make sure Arduino sketches build OK
	cd libraries/OlcbArduinoCAN/examples; make
	# build common C library and test
	cd libraries/OlcbTestCAN; make run

